// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: pkg/api/v1/internals/apiversion.proto

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package internals

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APIVersion represents the version of Bhojpur Application Runtime API.
type APIVersion int32

const (
	// unspecified apiversion
	APIVersion_APIVERSION_UNSPECIFIED APIVersion = 0
	// Bhojpur Application API v1
	APIVersion_V1 APIVersion = 1
)

// Enum value maps for APIVersion.
var (
	APIVersion_name = map[int32]string{
		0: "APIVERSION_UNSPECIFIED",
		1: "V1",
	}
	APIVersion_value = map[string]int32{
		"APIVERSION_UNSPECIFIED": 0,
		"V1":                     1,
	}
)

func (x APIVersion) Enum() *APIVersion {
	p := new(APIVersion)
	*p = x
	return p
}

func (x APIVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (APIVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_v1_internals_apiversion_proto_enumTypes[0].Descriptor()
}

func (APIVersion) Type() protoreflect.EnumType {
	return &file_pkg_api_v1_internals_apiversion_proto_enumTypes[0]
}

func (x APIVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use APIVersion.Descriptor instead.
func (APIVersion) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_v1_internals_apiversion_proto_rawDescGZIP(), []int{0}
}

var File_pkg_api_v1_internals_apiversion_proto protoreflect.FileDescriptor

var file_pkg_api_v1_internals_apiversion_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x76, 0x31, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x73, 0x2a, 0x30, 0x0a, 0x0a, 0x41, 0x50, 0x49, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x50, 0x49, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f,
	0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x56, 0x31, 0x10, 0x01, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x68, 0x6f, 0x6a, 0x70, 0x75, 0x72, 0x2f, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x3b, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_v1_internals_apiversion_proto_rawDescOnce sync.Once
	file_pkg_api_v1_internals_apiversion_proto_rawDescData = file_pkg_api_v1_internals_apiversion_proto_rawDesc
)

func file_pkg_api_v1_internals_apiversion_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_internals_apiversion_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_internals_apiversion_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_v1_internals_apiversion_proto_rawDescData)
	})
	return file_pkg_api_v1_internals_apiversion_proto_rawDescData
}

var file_pkg_api_v1_internals_apiversion_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_v1_internals_apiversion_proto_goTypes = []interface{}{
	(APIVersion)(0), // 0: v1.internals.APIVersion
}
var file_pkg_api_v1_internals_apiversion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_internals_apiversion_proto_init() }
func file_pkg_api_v1_internals_apiversion_proto_init() {
	if File_pkg_api_v1_internals_apiversion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_v1_internals_apiversion_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_api_v1_internals_apiversion_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_internals_apiversion_proto_depIdxs,
		EnumInfos:         file_pkg_api_v1_internals_apiversion_proto_enumTypes,
	}.Build()
	File_pkg_api_v1_internals_apiversion_proto = out.File
	file_pkg_api_v1_internals_apiversion_proto_rawDesc = nil
	file_pkg_api_v1_internals_apiversion_proto_goTypes = nil
	file_pkg_api_v1_internals_apiversion_proto_depIdxs = nil
}
