// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApplicationUIClient is the client API for ApplicationUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicationUIClient interface {
	// ListInstanceSpecs returns a list of Application Instance(s) that can be started through the UI.
	ListInstanceSpecs(ctx context.Context, in *ListInstanceSpecsRequest, opts ...grpc.CallOption) (ApplicationUI_ListInstanceSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type applicationUIClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationUIClient(cc grpc.ClientConnInterface) ApplicationUIClient {
	return &applicationUIClient{cc}
}

func (c *applicationUIClient) ListInstanceSpecs(ctx context.Context, in *ListInstanceSpecsRequest, opts ...grpc.CallOption) (ApplicationUI_ListInstanceSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ApplicationUI_ServiceDesc.Streams[0], "/v1.ApplicationUI/ListInstanceSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &applicationUIListInstanceSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ApplicationUI_ListInstanceSpecsClient interface {
	Recv() (*ListInstanceSpecsResponse, error)
	grpc.ClientStream
}

type applicationUIListInstanceSpecsClient struct {
	grpc.ClientStream
}

func (x *applicationUIListInstanceSpecsClient) Recv() (*ListInstanceSpecsResponse, error) {
	m := new(ListInstanceSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *applicationUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ApplicationUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationUIServer is the server API for ApplicationUI service.
// All implementations must embed UnimplementedApplicationUIServer
// for forward compatibility
type ApplicationUIServer interface {
	// ListInstanceSpecs returns a list of Application Instance(s) that can be started through the UI.
	ListInstanceSpecs(*ListInstanceSpecsRequest, ApplicationUI_ListInstanceSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedApplicationUIServer()
}

// UnimplementedApplicationUIServer must be embedded to have forward compatible implementations.
type UnimplementedApplicationUIServer struct {
}

func (UnimplementedApplicationUIServer) ListInstanceSpecs(*ListInstanceSpecsRequest, ApplicationUI_ListInstanceSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListInstanceSpecs not implemented")
}
func (UnimplementedApplicationUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedApplicationUIServer) mustEmbedUnimplementedApplicationUIServer() {}

// UnsafeApplicationUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationUIServer will
// result in compilation errors.
type UnsafeApplicationUIServer interface {
	mustEmbedUnimplementedApplicationUIServer()
}

func RegisterApplicationUIServer(s grpc.ServiceRegistrar, srv ApplicationUIServer) {
	s.RegisterService(&ApplicationUI_ServiceDesc, srv)
}

func _ApplicationUI_ListInstanceSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListInstanceSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationUIServer).ListInstanceSpecs(m, &applicationUIListInstanceSpecsServer{stream})
}

type ApplicationUI_ListInstanceSpecsServer interface {
	Send(*ListInstanceSpecsResponse) error
	grpc.ServerStream
}

type applicationUIListInstanceSpecsServer struct {
	grpc.ServerStream
}

func (x *applicationUIListInstanceSpecsServer) Send(m *ListInstanceSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ApplicationUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ApplicationUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationUI_ServiceDesc is the grpc.ServiceDesc for ApplicationUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ApplicationUI",
	HandlerType: (*ApplicationUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ApplicationUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListInstanceSpecs",
			Handler:       _ApplicationUI_ListInstanceSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "application-ui.proto",
}
