// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApplicationServiceClient is the client API for ApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicationServiceClient interface {
	// StartLocalInstance starts an Application Instance on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the application/config.yaml
	//   3. all bytes constituting the Instance YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalInstance(ctx context.Context, opts ...grpc.CallOption) (ApplicationService_StartLocalInstanceClient, error)
	// StartFromPreviousInstance starts a new Instance based on a previous one.
	// If the previous Instance does not have the can-replay condition set this call will result in an error.
	StartFromPreviousInstance(ctx context.Context, in *StartFromPreviousInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error)
	// StartInstanceRequest starts a new Instance based on its specification.
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error)
	// Searches for Instance(s) known to this instance
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	// Subscribe listens to new Instance(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (ApplicationService_SubscribeClient, error)
	// GetInstance retrieves details of a single Instance
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	// Listen listens to Instance updates and log output of a running Instance
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (ApplicationService_ListenClient, error)
	// StopInstance stops a currently running Instance
	StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error)
}

type applicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationServiceClient(cc grpc.ClientConnInterface) ApplicationServiceClient {
	return &applicationServiceClient{cc}
}

func (c *applicationServiceClient) StartLocalInstance(ctx context.Context, opts ...grpc.CallOption) (ApplicationService_StartLocalInstanceClient, error) {
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[0], "/v1.ApplicationService/StartLocalInstance", opts...)
	if err != nil {
		return nil, err
	}
	x := &applicationServiceStartLocalInstanceClient{stream}
	return x, nil
}

type ApplicationService_StartLocalInstanceClient interface {
	Send(*StartLocalInstanceRequest) error
	CloseAndRecv() (*StartInstanceResponse, error)
	grpc.ClientStream
}

type applicationServiceStartLocalInstanceClient struct {
	grpc.ClientStream
}

func (x *applicationServiceStartLocalInstanceClient) Send(m *StartLocalInstanceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *applicationServiceStartLocalInstanceClient) CloseAndRecv() (*StartInstanceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartInstanceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *applicationServiceClient) StartFromPreviousInstance(ctx context.Context, in *StartFromPreviousInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error) {
	out := new(StartInstanceResponse)
	err := c.cc.Invoke(ctx, "/v1.ApplicationService/StartFromPreviousInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*StartInstanceResponse, error) {
	out := new(StartInstanceResponse)
	err := c.cc.Invoke(ctx, "/v1.ApplicationService/StartInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, "/v1.ApplicationService/ListInstances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (ApplicationService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[1], "/v1.ApplicationService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &applicationServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ApplicationService_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type applicationServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *applicationServiceSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *applicationServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, "/v1.ApplicationService/GetInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (ApplicationService_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[2], "/v1.ApplicationService/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &applicationServiceListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ApplicationService_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type applicationServiceListenClient struct {
	grpc.ClientStream
}

func (x *applicationServiceListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *applicationServiceClient) StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (*StopInstanceResponse, error) {
	out := new(StopInstanceResponse)
	err := c.cc.Invoke(ctx, "/v1.ApplicationService/StopInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServiceServer is the server API for ApplicationService service.
// All implementations must embed UnimplementedApplicationServiceServer
// for forward compatibility
type ApplicationServiceServer interface {
	// StartLocalInstance starts an Application Instance on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the application/config.yaml
	//   3. all bytes constituting the Instance YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalInstance(ApplicationService_StartLocalInstanceServer) error
	// StartFromPreviousInstance starts a new Instance based on a previous one.
	// If the previous Instance does not have the can-replay condition set this call will result in an error.
	StartFromPreviousInstance(context.Context, *StartFromPreviousInstanceRequest) (*StartInstanceResponse, error)
	// StartInstanceRequest starts a new Instance based on its specification.
	StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResponse, error)
	// Searches for Instance(s) known to this instance
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	// Subscribe listens to new Instance(s) updates
	Subscribe(*SubscribeRequest, ApplicationService_SubscribeServer) error
	// GetInstance retrieves details of a single Instance
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	// Listen listens to Instance updates and log output of a running Instance
	Listen(*ListenRequest, ApplicationService_ListenServer) error
	// StopInstance stops a currently running Instance
	StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error)
	mustEmbedUnimplementedApplicationServiceServer()
}

// UnimplementedApplicationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApplicationServiceServer struct {
}

func (UnimplementedApplicationServiceServer) StartLocalInstance(ApplicationService_StartLocalInstanceServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalInstance not implemented")
}
func (UnimplementedApplicationServiceServer) StartFromPreviousInstance(context.Context, *StartFromPreviousInstanceRequest) (*StartInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousInstance not implemented")
}
func (UnimplementedApplicationServiceServer) StartInstance(context.Context, *StartInstanceRequest) (*StartInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedApplicationServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedApplicationServiceServer) Subscribe(*SubscribeRequest, ApplicationService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedApplicationServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedApplicationServiceServer) Listen(*ListenRequest, ApplicationService_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedApplicationServiceServer) StopInstance(context.Context, *StopInstanceRequest) (*StopInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedApplicationServiceServer) mustEmbedUnimplementedApplicationServiceServer() {}

// UnsafeApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationServiceServer will
// result in compilation errors.
type UnsafeApplicationServiceServer interface {
	mustEmbedUnimplementedApplicationServiceServer()
}

func RegisterApplicationServiceServer(s grpc.ServiceRegistrar, srv ApplicationServiceServer) {
	s.RegisterService(&ApplicationService_ServiceDesc, srv)
}

func _ApplicationService_StartLocalInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApplicationServiceServer).StartLocalInstance(&applicationServiceStartLocalInstanceServer{stream})
}

type ApplicationService_StartLocalInstanceServer interface {
	SendAndClose(*StartInstanceResponse) error
	Recv() (*StartLocalInstanceRequest, error)
	grpc.ServerStream
}

type applicationServiceStartLocalInstanceServer struct {
	grpc.ServerStream
}

func (x *applicationServiceStartLocalInstanceServer) SendAndClose(m *StartInstanceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *applicationServiceStartLocalInstanceServer) Recv() (*StartLocalInstanceRequest, error) {
	m := new(StartLocalInstanceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ApplicationService_StartFromPreviousInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).StartFromPreviousInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ApplicationService/StartFromPreviousInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).StartFromPreviousInstance(ctx, req.(*StartFromPreviousInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ApplicationService/StartInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).StartInstance(ctx, req.(*StartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ApplicationService/ListInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationServiceServer).Subscribe(m, &applicationServiceSubscribeServer{stream})
}

type ApplicationService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type applicationServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *applicationServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ApplicationService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ApplicationService/GetInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationServiceServer).Listen(m, &applicationServiceListenServer{stream})
}

type ApplicationService_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type applicationServiceListenServer struct {
	grpc.ServerStream
}

func (x *applicationServiceListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ApplicationService_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ApplicationService/StopInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).StopInstance(ctx, req.(*StopInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationService_ServiceDesc is the grpc.ServiceDesc for ApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ApplicationService",
	HandlerType: (*ApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousInstance",
			Handler:    _ApplicationService_StartFromPreviousInstance_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _ApplicationService_StartInstance_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _ApplicationService_ListInstances_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _ApplicationService_GetInstance_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _ApplicationService_StopInstance_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalInstance",
			Handler:       _ApplicationService_StartLocalInstance_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _ApplicationService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _ApplicationService_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "application.proto",
}
